# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turbidity_value', models.IntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name='Date accesed')),
                ('water', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='turbidity',
        ),
    ]
